export const AGENT_PROPERTIES_REQUEST ='AGENT_PROPERTIES_REQUEST'
export const AGENT_PROPERTIES_SUCCESS ='AGENT_PROPERTIES_SUCCESS'
export const AGENT_PROPERTIES_FAIL ='AGENT_PROPERTIES_FAIL'
export const AGENT_PROPERTIES_RESET='AGENT_PROPERTIES_RESET'

export const AGENT_PROPERTIES_DETAILS_REQUEST ='AGENT_PROPERTIES_DETAILS_REQUEST'
export const AGENT_PROPERTIES_DETAILS_SUCCESS ='AGENT_PROPERTIES_DETAILS_SUCCESS'
export const AGENT_PROPERTIES_DETAILS_FAIL ='AGENT_PROPERTIES_DETAILS_FAIL'
export const AGENT_PROPERTIES_DETAILS_RESET ='AGENT_PROPERTIES_DETAILS_RESET'


export const AGENT_CREATE_ACCOUNT_REQUEST ='AGENT_CREATE_ACCOUNT_REQUEST'
export const AGENT_CREATE_ACCOUNT_SUCCESS ='AGENT_CREATE_ACCOUNT_SUCCESS'
export const AGENT_CREATE_ACCOUNT_FAIL ='AGENT_CREATE_ACCOUNT_FAIL'
export const AGENT_CREATE_ACCOUNT_RESET='AGENT_CREATE_ACCOUNT_RESET'

export const AGENT_CREATE_PASSWORD_REQUEST ='AGENT_CREATE_PASSWORD_REQUEST'
export const AGENT_CREATE_PASSWORD_SUCCESS ='AGENT_CREATE_PASSWORD_SUCCESS'
export const AGENT_CREATE_PASSWORD_FAIL ='AGENT_CREATE_PASSWORD_FAIL'
export const AGENT_CREATE_PASSWORD_RESET ='AGENT_CREATE_PASSWORD_RESET'

export const AGENT_SIGNIN_REQUEST = 'AGENT_SIGNIN_REQUEST';
export const AGENT_SIGNIN_SUCCESS = 'AGENT_SIGNIN_SUCCESS';
export const AGENT_SIGNIN_FAIL = 'AGENT_SIGNIN_FAIL';

export const AGENT_SIGNOUT = 'AGENT_SIGNOUT';


export const GETQUOTE_REQUEST = 'GETQUOTE_REQUEST';
export const GETQUOTE_SUCCESS = 'GETQUOTE_SUCCESS';
export const GETQUOTE_FAIL = 'GETQUOTE_FAIL';


export const AGENT_BOOKING_REQUEST = 'AGENT_BOOKING_REQUEST';
export const AGENT_BOOKING_SUCCESS = 'AGENT_BOOKING_SUCCESS';
export const AGENT_BOOKING_FAIL = 'AGENT_BOOKING_FAIL';
export const AGENT_BOOKING_RESET = 'AGENT_BOOKING_RESET';


export const AGENT_BOOKING_DETAILS_REQUEST = 'AGENT_BOOKING_DETAILS_REQUEST';
export const AGENT_BOOKING_DETAILS_SUCCESS = 'AGENT_BOOKING_DETAILS_SUCCESS';
export const AGENT_BOOKING_DETAILS_FAIL = 'AGENT_BOOKING_DETAILS_FAIL';
export const AGENT_BOOKING_DETAILS_RESET = 'AGENT_BOOKING_DETAILS_RESET';

export const APPROVE_AGENT_BOOKING_REQUEST = 'APPROVE_AGENT_BOOKING_REQUEST';
export const APPROVE_AGENT_BOOKING_SUCCESS = 'APPROVE_AGENT_BOOKING_SUCCESS';
export const APPROVE_AGENT_BOOKING_FAIL = 'APPROVE_AGENT_BOOKING_FAIL';
export const APPROVE_AGENT_BOOKING_RESET = 'APPROVE_AGENT_BOOKING_RESET';

export const REJECT_AGENT_BOOKING_REQUEST = 'REJECT_AGENT_BOOKING_REQUEST';
export const REJECT_AGENT_BOOKING_SUCCESS = 'REJECT_AGENT_BOOKING_SUCCESS';
export const REJECT_AGENT_BOOKING_FAIL = 'REJECT_AGENT_BOOKING_FAIL';
export const REJECT_AGENT_BOOKING_RESET = 'REJECT_AGENT_BOOKING_RESET';


